// This file is auto-generated by TanStack Router.
// Regenerate by running: bun run dev (it will auto-generate on start)

import { createRootRoute, createRoute } from "@tanstack/react-router";

// Import route modules
import { Route as rootRoute } from "./routes/__root";
import { Route as IndexRoute } from "./routes/index";
import { Route as KioskIndexRoute } from "./routes/kiosk/index";
import { Route as KioskQrVisitIdRoute } from "./routes/kiosk/qr.$visitId";
import { Route as VisitVisitIdRoute } from "./routes/visit.$visitId";
import { Route as AdminLoginRoute } from "./routes/admin/login";
import { Route as AdminDashboardRoute } from "./routes/admin/dashboard";
import { Route as AdminScanRoute } from "./routes/admin/scan";

// Build the route tree
const rootRouteWithChildren = rootRoute.addChildren([
  IndexRoute,
  KioskIndexRoute,
  KioskQrVisitIdRoute,
  VisitVisitIdRoute,
  AdminLoginRoute,
  AdminDashboardRoute,
  AdminScanRoute,
]);

export const routeTree = rootRouteWithChildren;

// Route manifest for type safety
declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": { preLoaderRoute: typeof IndexRoute; parentRoute: typeof rootRoute };
    "/kiosk/": { preLoaderRoute: typeof KioskIndexRoute; parentRoute: typeof rootRoute };
    "/kiosk/qr/$visitId": { preLoaderRoute: typeof KioskQrVisitIdRoute; parentRoute: typeof rootRoute };
    "/visit/$visitId": { preLoaderRoute: typeof VisitVisitIdRoute; parentRoute: typeof rootRoute };
    "/admin/login": { preLoaderRoute: typeof AdminLoginRoute; parentRoute: typeof rootRoute };
    "/admin/dashboard": { preLoaderRoute: typeof AdminDashboardRoute; parentRoute: typeof rootRoute };
    "/admin/scan": { preLoaderRoute: typeof AdminScanRoute; parentRoute: typeof rootRoute };
  }
}
