/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as KioskIndexImport } from './routes/kiosk/index'
import { Route as VisitVisitIdImport } from './routes/visit.$visitId'
import { Route as AdminScanImport } from './routes/admin/scan'
import { Route as AdminLoginImport } from './routes/admin/login'
import { Route as AdminDashboardImport } from './routes/admin/dashboard'
import { Route as KioskQrVisitIdImport } from './routes/kiosk/qr.$visitId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const KioskIndexRoute = KioskIndexImport.update({
  id: '/kiosk/',
  path: '/kiosk/',
  getParentRoute: () => rootRoute,
} as any)

const VisitVisitIdRoute = VisitVisitIdImport.update({
  id: '/visit/$visitId',
  path: '/visit/$visitId',
  getParentRoute: () => rootRoute,
} as any)

const AdminScanRoute = AdminScanImport.update({
  id: '/admin/scan',
  path: '/admin/scan',
  getParentRoute: () => rootRoute,
} as any)

const AdminLoginRoute = AdminLoginImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRoute,
} as any)

const AdminDashboardRoute = AdminDashboardImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const KioskQrVisitIdRoute = KioskQrVisitIdImport.update({
  id: '/kiosk/qr/$visitId',
  path: '/kiosk/qr/$visitId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardImport
      parentRoute: typeof rootRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginImport
      parentRoute: typeof rootRoute
    }
    '/admin/scan': {
      id: '/admin/scan'
      path: '/admin/scan'
      fullPath: '/admin/scan'
      preLoaderRoute: typeof AdminScanImport
      parentRoute: typeof rootRoute
    }
    '/visit/$visitId': {
      id: '/visit/$visitId'
      path: '/visit/$visitId'
      fullPath: '/visit/$visitId'
      preLoaderRoute: typeof VisitVisitIdImport
      parentRoute: typeof rootRoute
    }
    '/kiosk/': {
      id: '/kiosk/'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskIndexImport
      parentRoute: typeof rootRoute
    }
    '/kiosk/qr/$visitId': {
      id: '/kiosk/qr/$visitId'
      path: '/kiosk/qr/$visitId'
      fullPath: '/kiosk/qr/$visitId'
      preLoaderRoute: typeof KioskQrVisitIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/scan': typeof AdminScanRoute
  '/visit/$visitId': typeof VisitVisitIdRoute
  '/kiosk': typeof KioskIndexRoute
  '/kiosk/qr/$visitId': typeof KioskQrVisitIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/scan': typeof AdminScanRoute
  '/visit/$visitId': typeof VisitVisitIdRoute
  '/kiosk': typeof KioskIndexRoute
  '/kiosk/qr/$visitId': typeof KioskQrVisitIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/scan': typeof AdminScanRoute
  '/visit/$visitId': typeof VisitVisitIdRoute
  '/kiosk/': typeof KioskIndexRoute
  '/kiosk/qr/$visitId': typeof KioskQrVisitIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/scan'
    | '/visit/$visitId'
    | '/kiosk'
    | '/kiosk/qr/$visitId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/scan'
    | '/visit/$visitId'
    | '/kiosk'
    | '/kiosk/qr/$visitId'
  id:
    | '__root__'
    | '/'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/scan'
    | '/visit/$visitId'
    | '/kiosk/'
    | '/kiosk/qr/$visitId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminScanRoute: typeof AdminScanRoute
  VisitVisitIdRoute: typeof VisitVisitIdRoute
  KioskIndexRoute: typeof KioskIndexRoute
  KioskQrVisitIdRoute: typeof KioskQrVisitIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminScanRoute: AdminScanRoute,
  VisitVisitIdRoute: VisitVisitIdRoute,
  KioskIndexRoute: KioskIndexRoute,
  KioskQrVisitIdRoute: KioskQrVisitIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin/dashboard",
        "/admin/login",
        "/admin/scan",
        "/visit/$visitId",
        "/kiosk/",
        "/kiosk/qr/$visitId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin/dashboard": {
      "filePath": "admin/dashboard.tsx"
    },
    "/admin/login": {
      "filePath": "admin/login.tsx"
    },
    "/admin/scan": {
      "filePath": "admin/scan.tsx"
    },
    "/visit/$visitId": {
      "filePath": "visit.$visitId.tsx"
    },
    "/kiosk/": {
      "filePath": "kiosk/index.tsx"
    },
    "/kiosk/qr/$visitId": {
      "filePath": "kiosk/qr.$visitId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
